<?php

add_action( 'init', function() {
	register_post_type( 'project', array(
		'labels' => array(
			'name' => 'Projects',
			'singular_name' => 'Project',
			'menu_name' => 'Projects',
			'all_items' => 'All Projects',
			'edit_item' => 'Edit Project',
			'view_item' => 'View Project',
			'view_items' => 'View Projects',
			'add_new_item' => 'Add New Project',
			'new_item' => 'New Project',
			'parent_item_colon' => 'Parent Project:',
			'search_items' => 'Search Projects',
			'not_found' => 'No projects found',
			'not_found_in_trash' => 'No projects found in Trash',
			'archives' => 'Project Archives',
			'attributes' => 'Project Attributes',
			'insert_into_item' => 'Insert into project',
			'uploaded_to_this_item' => 'Uploaded to this project',
			'filter_items_list' => 'Filter projects list',
			'filter_by_date' => 'Filter projects by date',
			'items_list_navigation' => 'Projects list navigation',
			'items_list' => 'Projects list',
			'item_published' => 'Project published.',
			'item_published_privately' => 'Project published privately.',
			'item_reverted_to_draft' => 'Project reverted to draft.',
			'item_scheduled' => 'Project scheduled.',
			'item_updated' => 'Project updated.',
			'item_link' => 'Project Link',
			'item_link_description' => 'A link to a project.',
		),
		'public' => true,
		'show_in_rest' => true,
		'menu_icon' => 'dashicons-layout',
		'supports' => array(
			0 => 'title',
			1 => 'author',
			2 => 'comments',
			3 => 'editor',
			4 => 'excerpt',
			5 => 'revisions',
			6 => 'page-attributes',
			7 => 'thumbnail',
			8 => 'custom-fields',
			9 => 'featured-image'
		),
		'delete_with_user' => false,
	) );
} );

add_action( 'acf/include_fields', function() {
	if ( ! function_exists( 'acf_add_local_field_group' ) ) {
		return;
	}

	acf_add_local_field_group( array(
		'key' => 'group_65060113f03bf',
		'title' => 'Details',
		'fields' => array(
			array(
				'key' => 'field_650602c1a3566',
				'label' => 'GitHub Repository',
				'name' => 'github_repository',
				'aria-label' => '',
				'type' => 'url',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
			),
			array(
				'key' => 'field_6506042ba3567',
				'label' => 'Website',
				'name' => 'website',
				'aria-label' => '',
				'type' => 'url',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
			),
			array(
				'key' => 'field_65060567a3568',
				'label' => 'Technology',
				'name' => 'technology',
				'aria-label' => '',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'table',
				'pagination' => 0,
				'min' => 0,
				'max' => 0,
				'collapsed' => '',
				'button_label' => 'Add Row',
				'rows_per_page' => 20,
				'sub_fields' => array(
					array(
						'key' => 'field_65060642a3569',
						'label' => 'Name',
						'name' => 'name',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'maxlength' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'parent_repeater' => 'field_65060567a3568',
					),
				),
			),
			array(
				'key' => 'field_65060696a356a',
				'label' => 'Visibility',
				'name' => 'visibility',
				'aria-label' => '',
				'type' => 'checkbox',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'public' => 'Public',
					'private' => 'Private',
				),
				'default_value' => array(
					0 => 'public',
				),
				'return_format' => 'value',
				'allow_custom' => 0,
				'layout' => 'vertical',
				'toggle' => 0,
				'save_custom' => 0,
				'custom_choice_button_text' => 'Add new choice',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'project',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'seamless',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	) );
} );

