name: Deploy Theme to Server

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "PasswordAuthentication yes" >> ~/.ssh/config
          echo "StrictHostKeyChecking no" >> ~/.ssh/config
          echo "User $SSH_USERNAME" >> ~/.ssh/config
          echo "HostName 208.87.134.120" >> ~/.ssh/config
          echo "Port 22" >> ~/.ssh/config
          echo "Password $SSH_PASSWORD" >> ~/.ssh/config
        env:
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}

      - name: Deploy Theme
        run: |
          scp -r ./* $SSH_USERNAME@208.87.134.120:/var/www/lloanalas.com/wp-content/themes/blog
        env:
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
