name: Deploy Theme to Server

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Copy repository contents via scp
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.SSH_USERNAME }}
        PORT: 22
        KEY: ${{ secrets.SSHKEY }}
      with:
        source: "."
        target: "/var/www/lloanalas.com/wp-content/themes/blog"

    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.SSH_USERNAME }}
        PORT: 22
        KEY: ${{ secrets.SSHKEY }}
        script: ls
